development:
  adapter: postgresql
  encoding: SQL_ASCII
  host: localhost
  database: hacknfortes_development
  pool: 5
  username: postgres
  password: 23Tfa023
  
test:
  adapter: postgresql
  encoding: SQL_ASCII
  host: localhost
  database: hacknfortes_test
  pool: 5
  username: postgres
  password: 23Tfa023