development:
  adapter: postgresql
  encoding: UTF-8
  database: hacknfortes_development
  pool: 5
  username: postgres
  password: 23Tfa023

test:
  adapter: postgresql
  encoding: UTF-8
  database: hacknfortes_test
  pool: 10
  username: postgres
  password: 23Tfa023

production:
  adapter: postgresql
  encoding: unicode
  database: hacknfortes_production
  pool: 5
  username: postgres
  password: 23Tfa023